In [1]:
import pandas as pd
import numpy as np

In [3]:
a=np.array([20,46,87,6,3,4,9,454,96,3])


In [5]:
a

array([ 20,  46,  87,   6,   3,   4,   9, 454,  96,   3])

In [7]:
a[-5:-12:-1]

array([ 4,  3,  6, 87, 46, 20])

In [9]:
a.ndim

1

In [11]:
b=np.random.randint(45,70,(7,8))

In [13]:
b

array([[60, 69, 65, 52, 49, 52, 50, 53],
       [65, 60, 65, 48, 59, 46, 69, 46],
       [66, 59, 49, 60, 55, 55, 51, 55],
       [60, 56, 58, 60, 55, 49, 57, 55],
       [65, 50, 63, 64, 54, 52, 59, 49],
       [68, 45, 47, 50, 63, 61, 60, 67],
       [56, 59, 64, 63, 69, 45, 48, 48]])

In [15]:
b[-4]

array([60, 56, 58, 60, 55, 49, 57, 55])

In [17]:
b.ndim

2

In [19]:
b[-1]

array([56, 59, 64, 63, 69, 45, 48, 48])

In [21]:
b[:,4]

array([49, 59, 55, 55, 54, 63, 69])

In [23]:
b[5,6] #5th row and 6 column

60

In [47]:
b[2]

array([66, 59, 49, 60, 55, 55, 51, 55])

In [ ]:
array [ row_start : row end : row step]

In [35]:
b

array([[60, 69, 65, 52, 49, 52, 50, 53],
       [65, 60, 65, 48, 59, 46, 69, 46],
       [66, 59, 49, 60, 55, 55, 51, 55],
       [60, 56, 58, 60, 55, 49, 57, 55],
       [65, 50, 63, 64, 54, 52, 59, 49],
       [68, 45, 47, 50, 63, 61, 60, 67],
       [56, 59, 64, 63, 69, 45, 48, 48]])

In [39]:
b[1:6:2,]

array([[65, 60, 65, 48, 59, 46, 69, 46],
       [60, 56, 58, 60, 55, 49, 57, 55],
       [68, 45, 47, 50, 63, 61, 60, 67]])

In [ ]:
array [ row_start : row end : row step , col_start : col _end : col_step]

In [43]:
b

array([[60, 69, 65, 52, 49, 52, 50, 53],
       [65, 60, 65, 48, 59, 46, 69, 46],
       [66, 59, 49, 60, 55, 55, 51, 55],
       [60, 56, 58, 60, 55, 49, 57, 55],
       [65, 50, 63, 64, 54, 52, 59, 49],
       [68, 45, 47, 50, 63, 61, 60, 67],
       [56, 59, 64, 63, 69, 45, 48, 48]])

In [49]:
b[1:6:2,1:6]

array([[60, 65, 48, 59, 46],
       [56, 58, 60, 55, 49],
       [45, 47, 50, 63, 61]])

In [51]:
b

array([[60, 69, 65, 52, 49, 52, 50, 53],
       [65, 60, 65, 48, 59, 46, 69, 46],
       [66, 59, 49, 60, 55, 55, 51, 55],
       [60, 56, 58, 60, 55, 49, 57, 55],
       [65, 50, 63, 64, 54, 52, 59, 49],
       [68, 45, 47, 50, 63, 61, 60, 67],
       [56, 59, 64, 63, 69, 45, 48, 48]])

In [53]:
b[1:6:2]

array([[65, 60, 65, 48, 59, 46, 69, 46],
       [60, 56, 58, 60, 55, 49, 57, 55],
       [68, 45, 47, 50, 63, 61, 60, 67]])

In [59]:
b[1:6:2, 1:8:3]

array([[60, 59, 46],
       [56, 55, 55],
       [45, 63, 67]])